=== cesarjorgerodriguez/C-sar_LND/LND1/2Trim/UD_7/DOSSIER/practica09_UD7.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="datoscoche"/>
	<xs:complexType name="datoscoche">
		<xs:sequence>
			<xs:element name="marca" type="xs:string"/>
			<xs:element name="modelo" type="xs:string"/>
			<xs:element name="puertas" type="xs:integer"/>
		</xs:sequence>
		<xs:attribute name="color">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="blanco"/>
					<xs:enumeration value="gris"/>
					<xs:enumeration value="rojo2"/>
					<xs:enumeration value="verde"/>
					<xs:enumeration value="azul"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="remesa">
		<xs:complexContent>
			<xs:extension base="datoscoche">
				<xs:sequence>
					<xs:element name="numcoches" type="xs:integer"/>
					<xs:element name="nombrebarco" type="xs:string"/>
					<xs:element name="paisproductor" type="xs:string"/>
					<xs:element name="paiscomprador" type="xs:string"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== cesarjorgerodriguez/C-sar_LND/LND1/2Trim/UD_7/DOSSIER/practica09_UD7.xml
<<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<datoscoche xsi:noNamespaceSchemaLocation="practica09_UD7.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<remesa>
		<numcoches>100</numcoches>
		<marca>Toyota LandCruiser</marca>
		<color>gris</color>
		<puertas>3</puertas>
		<paisproductor>Japon</paisproductor>
		<paiscomprador>Espa√±a</paiscomprador>
		<nombrebarco>SeaAdventurer</nombrebarco>
	</remesa>
</datoscoche>
