<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE pedidos [
<!ELEMENT pedidos ( cliente , articulo , pedido )* >
<!ATTLIST cliente idCliente CDATA "cli01" >
<!ELEMENT cliente ( nombre , apellidos )>
<!ELEMENT nombre ( #PCDATA )>
<!ELEMENT apellidos ( #PCDATA )>
<!ATTLIST articulo idArticulo CDATA "art01">
<!ELEMENT articulo ( nombre , descripcion? )>
<!ELEMENT descripcion ( #PCDATA )>
<!ATTLIST pedido idPedido CDATA "ped01" idCliente CDATA "cli01">
<!ELEMENT pedido ( articuloPedido , metodoPago , direccion )>
<!ATTLIST articuloPedido precio CDATA "1001" refArticulo CDATA "art01">
<!ELEMENT articuloPedido (#PCDATA)>
<!ELEMENT metodoPago ( tarjeta | transferencia )>
<!ATTLIST tarjeta titular CDATA "01">
<!ELEMENT tarjeta ( numero , fechaCaducidad , banco )>
<!ELEMENT numero ( #PCDATA )>
<!ELEMENT fechaCaducidad ( #PCDATA )>
<!ELEMENT banco (#PCDATA)>
<!ELEMENT direccion ( provincia , poblacion , calle , numero )>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT transferencia ( banco , numeroCuenta )>
<!ELEMENT numeroCuenta ( #PCDATA )>
]>
<pedidos>
      <cliente idCliente="cli01">
            <nombre>Luz</nombre>
            <apellidos>PeÃÅrez</apellidos>
      </cliente>

      <cliente idCliente="cli02">
            <nombre>Miranda</nombre>
            <apellidos>Gabriel</apellidos>
      </cliente>
      <articulo idArticulo="art01">
            <nombre>papas</nombre>
            <descripcion>saco de papas</descripcion>
      </articulo>
      <articulo idArticulo="art02">
            <nombre>boniatos</nombre>
            <descripcion>saco de batatas</descripcion>
      </articulo>
      <pedido idPedido="ped01" idCliente="cli01">
            <articuloPedido precio="1001" refArticulo="art01"></articuloPedido>
            <metodoPago>
                  <tarjeta titular="cli01">
                        <numero>123456789</numero>
                        <fechaCaducidad>01-01-2018</fechaCaducidad>
                        <banco></banco>
                  </tarjeta>
            </metodoPago>
            <direccion>
                  <provincia></provincia>
                  <poblacion></poblacion>
                  <calle></calle>
                  <numero></numero>
            </direccion>
      </pedido>
      <pedido idPedido="ped02" idCliente="cli02">
            <articuloPedido precio="1002" refArticulo="art02"></articuloPedido>
            <metodoPago>
                  <tarjeta titular="cli02">
                        <numero></numero>
                        <fechaCaducidad></fechaCaducidad>
                        <banco></banco>
                  </tarjeta>
            </metodoPago>
            <direccion>
                  <provincia></provincia>
                  <poblacion></poblacion>
                  <calle></calle>
                  <numero></numero>
            </direccion>
      </pedido>
      <pedido idPedido="ped03" idCliente="cli02">
            <articuloPedido precio="1003" refArticulo="art02"></articuloPedido>
            <metodoPago>
                  <tarjeta titular="cli02">
                        <numero></numero>
                        <fechaCaducidad></fechaCaducidad>
                        <banco></banco>
                  </tarjeta>
            </metodoPago>
            <direccion>
                  <provincia></provincia>
                  <poblacion></poblacion>
                  <calle></calle>
                  <numero></numero>
          </direccion>
        </pedido>
</pedidos>
